# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-08-16 14:12-0300\n"
"PO-Revision-Date: 2023-10-07 10:15-0300\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 3.3.2\n"

#: ui/MainWindow.glade:7
msgid "About"
msgstr "について"

#: ui/MainWindow.glade:11 ui/MainWindow.glade:238 ui/MainWindow.glade:275
#: ui/MainWindow.glade:747
msgid "Mauna USB Formatter"
msgstr "マウナ USB フォーマッタ"

#: ui/MainWindow.glade:14
msgid "Format USB Devices easily."
msgstr "USBデバイスを簡単にフォーマットします。"

#: ui/MainWindow.glade:52
msgid "Are you sure?"
msgstr "本気ですか？"

#: ui/MainWindow.glade:136
msgid "Will be formatted as:"
msgstr "次のようにフォーマットされます:"

#: ui/MainWindow.glade:176
msgid ""
"<b>WARNING:</b>\n"
"All the personal data on the device will be deleted.\n"
"Do you want to continue?"
msgstr ""
"<b>警告:</b>\n"
"デバイス上のすべての個人データが削除されます。\n"
"続けたいですか？"

#: ui/MainWindow.glade:434
msgid "New Device Name"
msgstr "新しいデバイス名"

#: ui/MainWindow.glade:451
msgid "Slow Format (Set all bytes to 0)"
msgstr "スローフォーマット (すべてのバイトを 0 に設定)"

#: ui/MainWindow.glade:478
msgid "Start"
msgstr "始める"

#: ui/MainWindow.glade:565 src/MainWindow.py:198
msgid "Formatting"
msgstr "書式設定"

#: ui/MainWindow.glade:581
msgid "This may take a while."
msgstr "これは時間がかかる場合があります。"

#: ui/MainWindow.glade:668 src/MainWindow.py:201
msgid "Formatting is finished."
msgstr "フォーマットが完了しました。"

#: ui/MainWindow.glade:694 src/MainWindow.py:201
msgid "You can eject the USB disk."
msgstr "USBディスクを取り出すことができます。"

#: ui/MainWindow.glade:704
msgid "Exit"
msgstr "出口"

#: ui/MainWindow.glade:722
msgid "Format another device."
msgstr "別のデバイスをフォーマットしてください。"

#: src/MainWindow.py:209
msgid "An error occured while formatting the disk."
msgstr "ディスクのフォーマット中にエラーが発生しました。"

#: src/MainWindow.py:212
msgid ""
"Please make sure the USB device is connected properly, not used by any "
"program and try again."
msgstr ""
"USB デバイスが正しく接続されており、どのプログラムによっても使用されて"
"いないことを確認して、再試行してください。"
